# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d352aadc62b3a3784144e473437be2cc0e7eca96a5e5a770124139fd29ada55ebcba7edf8ce8988b3eb70b5cf0d1255ed7d0f802a639a2a550269d29fa50718a

test:
  secret_key_base: 7c7fdf44aa249a24f66a68a782814fbb145ae1aff542d9f25005e87b1527a8f83289be5bf9645bba4f47533056cbe31944a8e8f40882a370bee373a722fc204e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
